analytics/urls.py
from django.contrib.auth import views as auth_views  # type: ignore
from django.urls import path  # type: ignore

from . import views

app_name = "analytics"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="index"),
    path("pulldown/", views.pulldown, name="pulldown"),
    path("update/", views.Update.as_view(), name="update"),
    path("accounts/login/", auth_views.LoginView.as_view()),
]

config/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('analytics.urls'))
]

# 開発環境での設定
if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

analytics/models.py
from django.contrib.auth import get_user_model  # type: ignore
from django.core.validators import FileExtensionValidator, MaxValueValidator, MinValueValidator  # type: ignore
from django.db import models  # type: ignore

from analytics.safety.function import decryption, encryption


class AnalyticsAppSettings(models.Model):
    CONTAINER_CHOICES = (
        ("", "無効"),
        ("container", "container"),
        ("container-sm", "container-sm"),
        ("container-fluid", "container-fluid"),
    )
    nav_title = models.CharField(
        verbose_name="ナビゲーションのタイトル",
        default="アナリティクス",
        max_length=50,
        help_text="ナビゲーションバーの左上に表記される文字",
    )
    heading_ja = models.CharField(
        verbose_name="日本語の見出し",
        default="ようこそアナリティクスページへ",
        max_length=100,
        help_text="画面中央頭に表記される見出し。日本語で記入してください。",
    )
    heading_us = models.CharField(
        verbose_name="英語の見出し",
        default="Welcome to analytics page",
        max_length=100,
        help_text="画面中央頭に表記される見出し。英語で記入してください。",
    )
    base_html_file = models.CharField(
        blank=True,
        null=True,
        verbose_name="ベースファイル",
        default="base.html",
        max_length=100,
        help_text="htmlファイルのベースとなるファイル名を入力してください。プロジェクト直下の場合は「base.html」。アプリ直下の場合は「app/base.html」。",
    )
    container = models.CharField(
        verbose_name="コンテナ",
        blank=True,
        default="container",
        max_length=15,
        choices=CONTAINER_CHOICES,
    )
    col_left = models.PositiveIntegerField(
        verbose_name="カラム左側",
        default=2,
        validators=[MaxValueValidator(9)],
        help_text="デフォルト値は２です",
    )
    col_center = models.PositiveIntegerField(
        verbose_name="カラム中央",
        default=8,
        validators=[MinValueValidator(3), MaxValueValidator(12)],
        help_text="デフォルト値は８です",
    )
    col_right = models.PositiveIntegerField(
        verbose_name="カラム右側",
        default=2,
        validators=[MaxValueValidator(9)],
        help_text="デフォルト値は２です",
    )

    def save(self, *args, **kwargs):
        """テンプレートファイルのベースファイル設定"""
        import os
        import re

        basehtml_file = "templates/analytics/base_index.html"
        file_dir = os.path.join(os.path.dirname(__file__), basehtml_file)
        with open(file_dir) as f:
            html_text = f.read()

        existing_name = re.search("^" + self.base_html_file, html_text)
        if not existing_name:
            # 既存のベース.htmlが検索されなければ新名と置き換え
            # 正規表現モジュールを使ってベースファイル名を置き換える
            comp = re.compile(r"extends \'\w+.html|extends \'\w+/\w+.html")
            html_text = comp.sub("extends '" + self.base_html_file, html_text)

            with open(file_dir, "w") as f:
                f.write(html_text)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.nav_title

    class Meta:
        verbose_name = "アナリティクスアプリの設定"
        verbose_name_plural = "アナリティクスアプリの設定"


class GoogleAnalytics4Config(models.Model):
    author = models.ForeignKey(
        get_user_model(),
        verbose_name="作成者",
        on_delete=models.CASCADE,
    )
    credential_path = models.FileField(
        blank=True,
        null=True,
        upload_to="analytics/",
        verbose_name="認証情報のファイルパス",
        validators=[
            FileExtensionValidator(
                [
                    "json",
                ]
            )
        ],
    )
    property_id = models.CharField(verbose_name="プロパティID", max_length=150)
    days_ago = models.PositiveIntegerField(
        verbose_name="日付の範囲",
        default=7,
        validators=[MaxValueValidator(30)],
    )

    def save(self, *args, **kwargs):
        # 保存する前にプロパティIDの暗号化
        try:
            self.property_id = encryption(self.property_id)
        except ValueError:
            # 既に暗号化されている場合は一度復号化してから再度暗号化して保存
            self.property_id = encryption(decryption(self.property_id))
        super().save(*args, **kwargs)

    def __str__(self):
        author = str(self.author)
        return author

    class Meta:
        verbose_name = "Googleアナリティクス4の構成"
        verbose_name_plural = "Googleアナリティクス4の構成"


class DimensionDate(models.Model):
    dates = models.DateField(verbose_name="日付")  # 西暦と月日を保存
    users = models.PositiveIntegerField(verbose_name="アクセス数")  # 0と正の整数を保存
    new_users = models.PositiveIntegerField(verbose_name="新規ユーザー数")
    page_views = models.PositiveIntegerField(verbose_name="ページビュー数")
    sessions = models.PositiveIntegerField(verbose_name="セッション数")
    ad_revenue = models.PositiveIntegerField(verbose_name="広告収益")
    ad_impressions = models.PositiveIntegerField(verbose_name="インプレッション数")

    def __str__(self):
        dates = str(self.dates)
        return dates

    class Meta:
        verbose_name = "アナリティクスデータ"
        verbose_name_plural = "アナリティクスデータ"


# Create your models here.

analytics/forms.py
from django import forms  # type: ignore

from .models import AnalyticsAppSettings


class AnalyticsAppSettingsForm(forms.ModelForm):
    class Meta:
        model = AnalyticsAppSettings
        fields = "__all__"

    def clean(self):
        col_sum = (
            self.cleaned_data["col_left"]
            + self.cleaned_data["col_center"]
            + self.cleaned_data["col_right"]
        )
        maxmum_col_val = 12
        if not col_sum <= maxmum_col_val:
            error_text = f"「レイアウト調整」のカラム総数が{col_sum}です。\n12に合わせる必要があります。"
            raise forms.ValidationError(error_text)

        return self.cleaned_data

analytics/views.py
from django.contrib import messages  # type: ignore
from django.contrib.auth.mixins import UserPassesTestMixin  # type: ignore
from django.http import JsonResponse  # type: ignore
from django.shortcuts import redirect, render  # type: ignore
from django.views.generic.base import View  # type: ignore
from django_pandas.io import read_frame  # type: ignore

from .models import AnalyticsAppSettings, DimensionDate, GoogleAnalytics4Config
from .update_api import update_data


class HomePageView(View):
    def get(self, request):
        context: dict = {}
        try:
            analytics_set = AnalyticsAppSettings.objects.all().last()
            dd_obj_all = DimensionDate.objects.all()
            # 値が存在するか
            dd_value_exist = dd_obj_all.exists()
            if dd_value_exist:
                # 値が存在すればデータフレームを作成する --------------------------
                df = read_frame(DimensionDate.objects.all())
                # 日付データを「年月」のフォーマットに変換
                df["dates"] = df["dates"].apply(lambda df: df.strftime("%Y年%m月"))
                # 日付データを元に日付以外のデータを集約する
                df = df.drop("id", axis=1).groupby(df["dates"]).sum()
                # テーブルに渡す用に、日付を降順にソートしたデータフレームを作成
                df_descending = df.sort_values("dates", ascending=False)
                # テンプレートへ渡すコンテキストデータに格納
                context["data_graph"] = df
                context["data_graph_subtitle"] = f"{df.index[0]} - {df.index[-1]}"
                context["data_table"] = df_descending
            context["analytics_set"] = analytics_set
            context["dd_exist"] = dd_value_exist
            template = "analytics/base_index.html"
            return render(request, template, context)
        except Exception as inst:
            Exception(inst)
            return render(request, "analytics/index.html", context)


def pulldown(request):
    """セレクトフォームによる非同期処理"""
    data_name = request.GET.get("data_name")
    date_value = request.GET.get("date_value")
    dd_obj_all = DimensionDate.objects.all()

    # フィールドのバーボスネーム取得
    for field in dd_obj_all.first()._meta.get_fields():
        if field.name == data_name:
            verbose_name = field.verbose_name

    df = read_frame(dd_obj_all)
    # 日付データを「年月」のフォーマットに変換
    df["dates"] = df["dates"].apply(lambda df: df.strftime("%Y年%m月"))
    # 日付データを元に日付以外のデータを集約する
    df = df.drop("id", axis=1).groupby(df["dates"]).sum()

    # グラフ用の処理 ----------------------------------------------
    # 日付の設定値を変える処理
    if date_value == "2":
        df = df[-12:]
    elif date_value == "3":
        df = df[-6:]

    if not request.user.is_staff:
        df.drop(["ad_revenue", "ad_impressions"], axis=1, inplace=True)

    # jsresponse用にリストを作成
    graph_data = [[index, data] for index, data in zip(df.index, df[data_name])]

    # テーブル用の処理 ---------------------------------------------
    # テーブルに渡す用に、日付を降順にソートしたデータフレームを作成
    df_descending = df.sort_values("dates", ascending=False)

    # # 日付の設定値を変える処理
    # if date_value == "2":
    #     df_descending = df_descending[:12]
    # elif date_value == "3":
    #     df_descending = df_descending[:6]

    # if not request.user.is_staff:
    #     df_descending.drop(["ad_revenue", "ad_impressions"], axis=1, inplace=True)

    # jsresponse用にリストを作成
    ls_data = [
        [index, data]
        for index, data in zip(df_descending.index, df_descending[data_name])
    ]

    return JsonResponse(
        {
            "data_table_head": verbose_name,
            "data_table": ls_data,
            "data_graph": graph_data,
        },
        status=200,
    )


class Update(UserPassesTestMixin, View):
    raise_exception = True

    def get(self, request):
        """アナリティクスデータの更新"""
        try:
            import os

            ga4_config = GoogleAnalytics4Config.objects.all().first()
            credential_filepath = ga4_config.credential_path.path
            os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = credential_filepath
            update_data.update_analyticsdata(ga4_config)
            messages.success(request, "アナリティクスデータの更新が完了しました")
            return redirect("analytics:index")
        except Exception:
            messages.error(request, "GoogleAnalytics4Configの設定ができていません")
            return redirect("analytics:index")

    def test_func(self):
        # スタッフユーザーでなければ４０３ページ
        return self.request.user.is_staff

analytics/templates/analytics/base_index.html
{% extends 'base.html' %}
{% load static %}

{% block analytics-style %}
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<!-- Bootstrap ICON -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
<!-- Original CSS -->
<link rel="stylesheet" href="{% static 'analytics/css/style.css' %}">
{% endblock analytics-style %}

{% block content %}
{% include 'analytics/include_index.html' %}
{% endblock content %}

analytics/templates/analytics/include_index.html
<!-- base_index.htmlとindex.htmlに含んでいる -->
{% if not analytics_set %}

<!-- アナリティクスアプリの初期設定が完了していな場合 -->
{% include 'analytics/include_not_analytics_set.html' %}

{% else %}
{% if user.is_staff %}
<!-- Nav Message Modal -->
{% include 'analytics/include_nav_message_modal.html' %}
{% endif %}

<!-- Container -->
<div class="{{ analytics_set.container }}">
  <div class="row">
    <div class="col-{{ analytics_set.col_left }}">
      <!-- Bootstrap グリッドシステム左側 -->
    </div>
    <div class="col-lg-{{ analytics_set.col_center }} col-12">
      <!-- Bootstrap グリッドシステム中央 -->

      <!-- Heading -->
      <figure class="text-center figure-analytics">
	<blockquote class="blockquote">
	  <p>{{ analytics_set.heading_ja }}</p>
	  <figcaption class="blockquote-footer">
	    {{ analytics_set.heading_us }}
	  </figcaption>
	</blockquote>
      </figure>

      {% if not dd_exist %}
      <!-- アナリティクスデータが空だった場合 -->
      <figure class="text-center figure-analytics">
	<blockquote class="blockquote">
	  <i class="bi bi-cone-striped" style="font-size: 400%; color: red;"></i><h1 class="display-1-analytics">準備中...</h1>
	</blockquote>
	<figcaption class="blockquote-footer">
	  in preparation
	</figcaption>
      </figure>

      {% else %}
      <!-- Select Form -->
      <form class="form-analytics" id="ajax_chenge" action="{% url 'analytics:pulldown' %}" method="GET">
	<div class="row">
	  <div class="col">
	    <select id="select_data" class="form-select" aria-label="Default select example" onclick='document.getElementById("ch_servings_submit").click();'>

	      <!-- option selected>データ名</option -->
	      <option value="users">アクセス数</option>
	      <option value="new_users">新規ユーザー数</option>
	      <option value="page_views">ページビュー数</option>
	      <option value="sessions">セッション数</option>
	      {% if user.is_staff %}
	      <option value="ad_revenue">広告収益</option>
	      <option value="ad_impressions">インプレッション数</option>
	      {% endif %}
	    </select>
	  </div>
	  <div class="col">
	    <select id="select_date" class="form-select" aria-label="Default select example" onclick='document.getElementById("ch_servings_submit").click();'>
	      <option selected>日付</option>
	      <option value="1">全て</option>
	      <option value="2">１年前から現在</option>
	      <option value="3">半年前から現在</option>
	    </select>
	  </div>
	</div>
	<input type="submit" value="送信" id="ch_servings_submit" style="display:none;">
      </form>

      <!-- Google Charts -->
      <div id="chart_div"></div>

      <!-- Table -->
      <div class="table-scroll-analytics" id="table-scroll-analytics">
	<table class="table table-analytics table-hover">
	  <thead>
	    <tr>
	      <th scope="col">日付</th>
	      <th id="table_head" scope="col">アクセス数</th>
	    </tr>
	  </thead>
	  <tbody id="data_table" class="table-group-divider">
	    {% for index, row in data_table.iterrows %}
	    <tr>
	      <th scope="row">{{ index }}</th>
	      <td>{{ row.users }}</td>
	    </tr>
	    {% endfor %}
	  </tbody>
	</table>
      </div>

      {% endif %}
    </div>
    <div class="col-{{ analytics_set.col_right }}">
      <!-- Bootstrap グリッドシステム右側 -->
    </div>
  </div>
</div>

<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
{% if dd_exist %}
<!-- data_graphデータフレームが空でなければ読み込む -->
<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.7.1.js"></script>
<!-- Google Charts -->
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
$('#ajax_chenge').on('submit', e => {
  e.preventDefault();

  // Ajax処理
  $.ajax({
    'url': "{% url 'analytics:pulldown' %}",
    'type': 'GET',
    'data': {
      'data_name': $('#select_data').val(),
      'date_value': $('#select_date').val(),
    },
    'dataType': 'json'
  }).done(response => {
    // Google Charts
    google.charts.load('current', {'packages':['bar']});
    google.charts.setOnLoadCallback(drawChart);
    let chart_array = [['日付', response.data_table_head]]
    for (const graph of response.data_graph) {
      chart_array.push(graph)
    }
    function drawChart() {
      var data = google.visualization.arrayToDataTable(chart_array);

      var options = {
	chart: {
	  title: response.data_table_head,
	  // 2xxx年x月-2xxx年x月
	  subtitle: chart_array[1][0]+'-'+chart_array[chart_array.length-1][0],
	},
	colors: ['#33ac71'],
	width: '100%',// グラフの横長
	height: 400,// グラフの縦長
	vAxis: {format: 'decimal'},// 左側軸のフォーマット
	hAxis: {textPosition: 'out', title: ''},
	legend: { position: 'none', textStyle: {fontSize: 10}},// 凡例の位置（'none'しか効かない）
      };
      var chart = new google.charts.Bar(document.getElementById('chart_div'));
      chart.draw(data, google.charts.Bar.convertOptions(options));
    }

    // テーブル処理
    if (response.data_table.length <= 12){
      $('.table-scroll-analytics').removeAttr('class'); // スクロール指定した属性を削除
    }else{
      $('#table-scroll-analytics').attr('class', 'table-scroll-analytics'); // スクロールを有効にする
    }
    $('#table_head').empty(); // #table_head内の要素を削除
    $('#data_table').empty(); // #data_table内の要素を削除

    $('#table_head').text(response.data_table_head); // #table_head内に要素を追加
    // ループ処理
    for (const table of response.data_table) {
      // 必要なテーブルタグを作成
      const tr = $('<tr>');
      const th = $('<th>', { scop:'row', text: table[0] });
      const td = $('<td>', {text: table[1]});
      // #data_table内にテーブルを追加
      $('#data_table').append(tr.append(th).append(td));
    }
  });
});
// デフォルトのGoogle Chart
google.charts.load('current', {'packages':['bar']});
google.charts.setOnLoadCallback(drawChart);

function drawChart() {
  var data = google.visualization.arrayToDataTable([
    ['日付', 'アクセス数'],
    {% for index, row in data_graph.iterrows %}
    ['{{ index }}', {{ row.users }}],
    {% endfor %}
  ]);

  // セレクトフォームの実装次第で「202402」のような要素だった場合、アクシズ（hAxis）のフォーマットを変更する。
  var options = {
    chart: {
      title: 'アクセス数',
      subtitle: '{{ data_graph_subtitle }}',//'2024年1月-2024年12月',
    },
    colors: ['#33ac71'],
    width: '100%',// グラフの横長
    height: 400,// グラフの縦長
    vAxis: {format: 'decimal'},// 左側軸のフォーマット
    hAxis: {textPosition: 'out', title: ''},
    legend: { position: 'none', textStyle: {fontSize: 10}},// 凡例の位置（'none'しか効かない）
  };

  var chart = new google.charts.Bar(document.getElementById('chart_div'));

  chart.draw(data, google.charts.Bar.convertOptions(options));
}
</script>
<!-- data_graphデータフレームが空でなければ読み込む -->
{% endif %}
<!-- アナリティクスアプリの初期設定が完了しているか　-->
{% endif %}

analytics/templates/analytics/include_nav_message_modal.html
<nav class="navbar nav-analytics sticky-top">
  <div class="container-fluid">
    <h4>{% block title %}{{ analytics_set.nav_title }}{% endblock title %}</h4>
    <ul class="nav justify-content-end">
      <li class="nav-item">
	<li class="nav-item dropdown">
	  <a title="諸設定" class="nav-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-gear" style="font-size:150%; color:limegreen;"></i>
          </a>
          <ul class="dropdown-menu">
	    <li><a class="dropdown-item" href="{% url 'admin:analytics_analyticsappsettings_change' analytics_set.id %}">アプリ設定</a></li>
	    <li><a class="dropdown-item" href="{% url 'admin:analytics_googleanalytics4config_change' request.user.id %}">GA4設定</a></li>
          </ul>
        </li>
	<button title="アップデート" type="button" class="btn btn-defult" data-bs-toggle="modal" data-bs-target="#exampleModal">
	  <i class="bi bi-arrow-clockwise" style="font-size:150%; color:limegreen;"></i>
	</button>
      </li>
    </ul>
  </div>
</nav>

<!-- Message -->
{% if messages %}
<div class="alert alert-danger" role="alert">
  {% for message in messages %}
  <strong>{{ message }}</strong>
  {% endfor %}
</div>
{% endif %}

<!-- Modal -->
<form action="{% url 'analytics:update' %}" method="GET">
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
	<div class="modal-header">
	  <h1 class="modal-title fs-5" id="exampleModalLabel">
	    <blockquote class="blockquote">
	      <p>確認画面</p>
	      <figcaption class="blockquote-footer">
		Confirmation
	      </figcaption>
	    </blockquote>
	  </h1>
	  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
	</div>
	<div class="modal-body">
	  <blockquote class="blockquote">
	    <p>アナリティクスデータの更新を実行しますか？</p>
	    <figcaption class="blockquote-footer">
	      Would you like to update your analytics data?
	    </figcaption>
	  </blockquote>
	</div>
	<div class="modal-footer">
	  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">やめる</button>
	  <button type="submit" class="btn btn-success">更新</button>
	</div>
      </div>
    </div>
  </div>
</form>

analytics/templates/analytics/include_not_analytics_set.html
<div class="card text-center">
  <div class="card-header">
    <i class="bi bi-exclamation-triangle" style="font-size: 200%;"></i>
  </div>
  <div class="card-body card-body-analytics">
    <blockquote class="blockquote">
      <p class="card-title">アプリケーションの初期設定ができていません。</p>
      <figcaption class="blockquote-footer">
	Initial settings for the application have not been completed.
      </figcaption>
    </blockquote>
    <blockquote class="blockquote">
      <p class="card-text">初期設定の流れ</p>
      <figcaption class="blockquote-footer">
	Initial setup flow
      </figcaption>
    </blockquote>

    <pre><code>
	$ python3 manage.py migrate
	$ python3 manage.py createsuperuser
	$ python3 manage.py analytics_set
	アナリティクスアプリの初期設定完了
    </code></pre>

    <a href="https://github.com/kenno-warise/zfl-analytics/blob/main/README.md" class="btn btn-default">
      ドキュメント <i class="bi bi-github"></i>
    </a>
  </div>
  <div class="card-footer text-body-secondary">
    <i class="bi bi-exclamation-triangle" style="font-size: 200%;"></i>
  </div>
</div>

analytics/templates/analytics/index.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{{ analytics_set.nav_title }}{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <!-- Bootstrap ICON -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <!-- Original CSS -->
    <link rel="stylesheet" href="{% static 'analytics/css/style.css' %}">

  </head>
  <body>
    {% include 'analytics/include_index.html' %}
  </body>
</html>